config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/OpenPDAC-12:
      branch: main
      repo: https://github.com/demichie/OpenPDAC-12
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/OpenPDAC-12 git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tomato-cougar.sh
        container: qc.acc_smelly-lilac-hound
  QC.Doc:
    repos:
      github.com/demichie/OpenPDAC-12 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-celadon-quoll.sh
        container: qc.doc_pretty-grey-rat
      github.com/demichie/OpenPDAC-12 git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sepia-setter.sh
        container: qc.doc_cranky-platinum-bonobo
      github.com/demichie/OpenPDAC-12 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cardinal-moose.sh
        container: qc.doc_pasty-gold-gopher
  QC.Lic:
    repos:
      github.com/demichie/OpenPDAC-12 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-apricot-avocet.sh
        container: qc.lic_shaky-purple-snake
  QC.Met:
    repos:
      github.com/demichie/OpenPDAC-12 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-pink-dog.sh
        container: qc.met_droopy-pear-termite
  QC.Sec:
    repos:
      github.com/demichie/OpenPDAC-12 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-silver-quoll.sh
        container: qc.sec_gloppy-sapphire-newfoundland
  QC.Sty:
    repos:
      github.com/demichie/OpenPDAC-12 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-goldenrod-javanese.sh
        container: qc.sty_cloudy-firebrick-llama
      github.com/demichie/OpenPDAC-12 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-white-uakari.sh
        container: qc.sty_frumpy-chestnut-manatee
  QC.Uni:
    repos:
      github.com/demichie/OpenPDAC-12 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-jade-hedgehog.sh
        container: qc.uni_zippy-crimson-akita
  QC.Ver:
    repos:
      github.com/demichie/OpenPDAC-12 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-auburn-mandrill.sh
        container: qc.ver_randy-cinnamon-spider
timeout: 5400
